apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: poc
  source:
    repoURL: https://github.com/JaimeHenaoChallange/frontend.git
    targetRevision: HEAD
    path: helm-charts/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
